<<<<<<< HEAD
name: Deploy Vite to GitHub Pages
=======
name: Build and deploy site to root
>>>>>>> a790006 (chore: add CI to build React app subfolder and deploy to root)

on:
  push:
    branches: [ main ]
<<<<<<< HEAD
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install and build
        run: |
          npm ci
          npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
=======
    paths:
      - 'Therocky001.github.io/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: pages-deploy
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: Therocky001.github.io/package-lock.json

      - name: Install dependencies
        working-directory: Therocky001.github.io
        run: npm ci

      - name: Build site
        working-directory: Therocky001.github.io
        run: npm run build

      - name: Prepare root for new build
        run: |
          rm -rf assets
          rm -f index.html
          rm -f index-test.html
        working-directory: .

      - name: Copy build to repository root
        working-directory: Therocky001.github.io
        run: cp -r dist/* ../

      - name: Commit and push changes to main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Deploy built site from subfolder [skip ci]"
            git push
          fi
>>>>>>> a790006 (chore: add CI to build React app subfolder and deploy to root)
